/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BorrowAndReturnManager.ReturnManager.View;

import BorrowAndReturnManager.ReturnManager.Model.mdl_phieutrasach;
import LoginAndRegister.MyConnection;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class jf_phieutrasach extends javax.swing.JFrame {

    public jf_phieutrasach() {
        initComponents();
        addPlaceholderStyle(jtfSearch);
        getListPHIEUTRASACH();
        this.setLocationRelativeTo(null);
        this.setTitle("Return Manager");
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        jpnView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTableModel = new javax.swing.JTable();
        btnReload = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(251, 224, 196));

        btnDelete.setBackground(new java.awt.Color(114, 158, 190));
        btnDelete.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(114, 158, 190));
        btnAdd.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jtfSearch.setFont(new java.awt.Font("SF Pro Display", 2, 12)); // NOI18N
        jtfSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfSearch.setText("Search");
        jtfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSearchFocusLost(evt);
            }
        });
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
        });

        classTableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    Mã phiếu trả sách", "             Ngày trả", " Mã phiếu mượn sách", "    Tiền phạt kỳ này", "      Tiền nợ kỳ này", "      Tổng nợ kỳ này"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classTableModel);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnReload.setBackground(new java.awt.Color(114, 158, 190));
        btnReload.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnReload.setText("Reload");
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReloadMouseExited(evt);
            }
        });
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(114, 158, 190));
        btnPrint.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(78, Short.MAX_VALUE)
                    .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(new Color(79,110,133));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(114,158,190));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel defaultTable = (DefaultTableModel) classTableModel.getModel();
        if(classTableModel.getSelectedRowCount() == 1) {
            int confirmed = JOptionPane.showConfirmDialog(null, 
                "Are you sure you want to delete it?", "Delete Message Box",
                JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                int index = classTableModel.getSelectedRow();
                TableModel model = classTableModel.getModel();
                int MAPHIEUTRASACH_selected = Integer.parseInt(model.getValueAt(index, 0).toString());
                int MAPHIEUMUONSACH_selected = Integer.parseInt(model.getValueAt(index, 2).toString());
                double TIENPHATKYNAY = 0;
                double TONGNODOCGIA = 0;
                PreparedStatement ps1;
                ResultSet rs1;
                String query1 = "Select MASACH from ctphieumuonsach where MAPHIEUMUONSACH = '" + MAPHIEUMUONSACH_selected + "';";
            
                PreparedStatement ps2;
                ResultSet rs2;
                String query2 = "Select TIENPHATKYNAY from phieutrasach where MAPHIEUTRASACH = '" + MAPHIEUTRASACH_selected + "';";
            
                PreparedStatement ps3;
                ResultSet rs3;
                String query3 = "Select TONGNODOCGIA from thedocgia T join phieumuonsach P on T.MADOCGIA = P.MADOCGIA where MAPHIEUMUONSACH = '" + MAPHIEUMUONSACH_selected + "';";
            
                PreparedStatement ps4;
                int rs4;
                String query4 = "UPDATE thedocgia SET TONGNODOCGIA=? WHERE MADOCGIA = (Select MADOCGIA from phieumuonsach where MAPHIEUMUONSACH = '" + MAPHIEUMUONSACH_selected + "');";
            
                PreparedStatement ps5;
                int rs5;
                String query5 = "Delete from ctphieutrasach where MAPHIEUTRASACH = '" + MAPHIEUTRASACH_selected + "';";
            
                PreparedStatement ps6;
                int rs6;
                String query6 = "Delete from phieutrasach where MAPHIEUTRASACH = '" + MAPHIEUTRASACH_selected + "';";
                try {
                    ps1 = MyConnection.getConnection().prepareStatement(query1);
                    rs1 = ps1.executeQuery();
                    while (rs1.next()) {
                    int MASACH = rs1.getInt("MASACH");
                    int rs;
                    String query = "UPDATE thongtinsach SET TRANGTHAI=? WHERE MASACH = '" + MASACH + "';";
                    PreparedStatement ps = MyConnection.getConnection().prepareStatement(query);
                    ps.setInt(1, 1);
                    rs = ps.executeUpdate();
                    ps.close();
                    if(rs > 0) {}
                     else JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi cập nhật trạng thái sách khi xóa phiếu trả sách!!!");
                    }
                    ps1.close();
                    rs1.close();
                
                    ps2 = MyConnection.getConnection().prepareStatement(query2);
                    rs2 = ps2.executeQuery();
                    while (rs2.next()) {
                    TIENPHATKYNAY = rs2.getDouble("TIENPHATKYNAY");
                    }
                    ps2.close();
                    rs2.close();
                
                    ps3 = MyConnection.getConnection().prepareStatement(query3);
                    rs3 = ps3.executeQuery();
                    while (rs3.next()) {
                        TONGNODOCGIA = rs3.getDouble("TONGNODOCGIA");
                    }
                    ps3.close();
                    rs3.close();
                
                    ps4 = MyConnection.getConnection().prepareStatement(query4);
                    ps4.setDouble(1, TONGNODOCGIA - TIENPHATKYNAY);
                    rs4 = ps4.executeUpdate();
                    ps4.close();
                    if(rs4 > 0) {
                        ps5 = MyConnection.getConnection().prepareStatement(query5);
                        rs5 = ps5.executeUpdate();
                        ps5.close();
                        if(rs5 > 0) {
                            ps6 = MyConnection.getConnection().prepareStatement(query6);
                            rs6 = ps6.executeUpdate();
                            ps6.close();
                            if(rs6 > 0) {
                                defaultTable.removeRow(classTableModel.getSelectedRow());
                                JOptionPane.showMessageDialog(null, "Đã xóa phiếu trả sách thành công!!!");
                            }
                            else JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi xóa phiếu trả sách!!!");
                        }
                        else JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi xóa chi tiết phiếu trả sách!!!");
                    }
                    else JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi cập nhật tổng nợ độc giả khi xóa phiếu trả sách!!!");
                
                } catch (SQLException e) {
                }
            }
            else { setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); }
            
        }
        else {
            if(classTableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Không còn hàng nào để xóa!!!");
            }
            else JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa!!!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(new Color(79,110,133));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(new Color(114,158,190));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        jf_add frame = new jf_add();
        frame.setTitle("Return Manager - Add");
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSearchFocusGained
        if(jtfSearch.getText().equals("Search")) {
            jtfSearch.setText(null);
            jtfSearch.requestFocus();
            removePlaceholderStyle(jtfSearch);
        }
    }//GEN-LAST:event_jtfSearchFocusGained

    private void jtfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSearchFocusLost
        if(jtfSearch.getText().length() == 0) {
            addPlaceholderStyle(jtfSearch);
            jtfSearch.setText("Search");
        }
    }//GEN-LAST:event_jtfSearchFocusLost

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyReleased
        String key = jtfSearch.getText().trim();
       DefaultTableModel model = (DefaultTableModel) classTableModel.getModel();
       TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
       classTableModel.setRowSorter(tr);
       tr.setRowFilter(RowFilter.regexFilter(key, 0));
    }//GEN-LAST:event_jtfSearchKeyReleased

    private void btnReloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseEntered
        btnReload.setBackground(new Color(79,110,133));
    }//GEN-LAST:event_btnReloadMouseEntered

    private void btnReloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseExited
        btnReload.setBackground(new Color(114,158,190));
    }//GEN-LAST:event_btnReloadMouseExited

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        DefaultTableModel model = (DefaultTableModel) classTableModel.getModel();
        model.setRowCount(0);
        getListPHIEUTRASACH();
        JOptionPane.showMessageDialog(null, "Đã làm mới lại danh sách phiếu trả sách!!!");
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        btnPrint.setBackground(new Color(79,110,133));
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        btnPrint.setBackground(new Color(114,158,190));
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        DefaultTableModel defaultTable = (DefaultTableModel) classTableModel.getModel();
        if(classTableModel.getSelectedRowCount() == 1) {
            int index = classTableModel.getSelectedRow();
            Print(index);
        }
        else {
            if(classTableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Không còn hàng nào để in!!!");
            }
            else JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để in!!!");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon(this.getClass().getClassLoader().getResource("assets/borrow_and_return.png"));
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null, 
            "Do you want to exit Return Books?", "Exit Return Books",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        else { setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); }
    }//GEN-LAST:event_formWindowClosing

    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public void getListPHIEUTRASACH() {
	DefaultTableModel defaultTable = (DefaultTableModel) classTableModel.getModel();
	List<mdl_phieutrasach> phieutrasachList = new ArrayList<>();
        PreparedStatement ps;
        ResultSet rs;
        String query = "Select * from phieutrasach;";
        String pattern = "###,###.###";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
	try {
            ps = MyConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            while (rs.next()) {
		int MAPHIEUTRASACH = rs.getInt("MAPHIEUTRASACH");
		String NGAYTRA = rs.getString("NGAYTRA");
                int MAPHIEUMUONSACH = rs.getInt("MAPHIEUMUONSACH");
                int TIENPHATKYNAY = (int) rs.getDouble("TIENPHATKYNAY");
                int TIENNOKYNAY = (int) rs.getDouble("TIENNOKYNAY");
                int TONGNO = (int) rs.getDouble("TONGNO");
		mdl_phieutrasach phieutrasach = new mdl_phieutrasach(MAPHIEUTRASACH, NGAYTRA, MAPHIEUMUONSACH, TIENPHATKYNAY, TIENNOKYNAY, TONGNO);
		phieutrasachList.add(phieutrasach);
            }	
            Object[] row = new Object[6];
            for(int i = 0; i <phieutrasachList.size(); i++) {
		row[0] = phieutrasachList.get(i).getMAPHIEUTRASACH();
		row[1] = phieutrasachList.get(i).getNGAYTRA();
                row[2] = phieutrasachList.get(i).getMAPHIEUMUONSACH();
                row[3] = decimalFormat.format(phieutrasachList.get(i).getTIENPHATKYNAY());
                row[4] = decimalFormat.format(phieutrasachList.get(i).getTIENNOKYNAY());
                row[5] = decimalFormat.format(phieutrasachList.get(i).getTONGNO());
		defaultTable.addRow(row);
            }
            ps.close();
            rs.close();
	} catch (SQLException e) {
	}
    }
    
    public static String removeVietnameseLetters(String str) {
    str = str.replaceAll("à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ", "a");
    str = str.replaceAll("è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ", "e");
    str = str.replaceAll("ì|í|ị|ỉ|ĩ", "i");
    str = str.replaceAll("ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ", "o");
    str = str.replaceAll("ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ", "u");
    str = str.replaceAll("ỳ|ý|ỵ|ỷ|ỹ", "y");
    str = str.replaceAll("đ", "d");
    str = str.replaceAll("À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ", "A");
    str = str.replaceAll("È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ", "E");
    str = str.replaceAll("Ì|Í|Ị|Ỉ|Ĩ", "I");
    str = str.replaceAll("Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ", "O");
    str = str.replaceAll("Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ", "U");
    str = str.replaceAll("Ỳ|Ý|Ỵ|Ỷ|Ỹ", "Y");
    str = str.replaceAll("Đ", "D");
    return str;
}
    
    public void Print(int index) {
        TableModel model = classTableModel.getModel();
        String maphieutrasach = model.getValueAt(index, 0).toString();
        String ngaytra = model.getValueAt(index, 1).toString();
        String maphieumuonsach = model.getValueAt(index, 2).toString();
        String tienphatkynay = model.getValueAt(index, 3).toString();
        String tiennokynay = model.getValueAt(index, 4).toString();
        String tongno = model.getValueAt(index, 5).toString();
        
        String hoten = "";
        PreparedStatement ps1;
        ResultSet rs1;
        String query1 = "Select HOTEN from thedocgia T join phieumuonsach P on T.MADOCGIA = P.MADOCGIA where MAPHIEUMUONSACH = '" + maphieumuonsach + "';";
        try {
            ps1 = MyConnection.getConnection().prepareStatement(query1);
            rs1 = ps1.executeQuery();
            while (rs1.next()) {
		hoten = removeVietnameseLetters(rs1.getString("HOTEN").trim());
            }	
            ps1.close();
            rs1.close();
	} catch (SQLException e) {
	}
        
        int songaytratre = 0;
        PreparedStatement ps2;
        ResultSet rs2;
        String query2 = "Select SONGAYTRATRE from ctphieutrasach where MAPHIEUTRASACH = '" + maphieutrasach + "';";
        try {
            ps2 = MyConnection.getConnection().prepareStatement(query2);
            rs2 = ps2.executeQuery();
            while (rs2.next()) {
		songaytratre = rs2.getInt("SONGAYTRATRE");
            }	
            ps2.close();
            rs2.close();
	} catch (SQLException e) {
	}
        
        String path = "D:\\";
        Document doc = new Document() {};
        try{
           PdfWriter.getInstance(doc, new FileOutputStream(path+"PHIEUTRASACHSO"+maphieutrasach+".pdf"));
           doc.open();
           Paragraph p1 = new Paragraph("                                           BOOK RETURN BILL\n");
           doc.add(p1);
           Paragraph p2 = new Paragraph("                      ****************************************************************************");
           doc.add(p2);
           Paragraph p3 = new Paragraph("\t    *General Information " + "\nName: "+ hoten + "\nReturn Bill Id: " + maphieutrasach 
                + "\nBorrow Bill Id: "+ maphieumuonsach);
           doc.add(p3);
           doc.add(p2);
           Paragraph p5 = new Paragraph("\t    *Details " + "\nThe number of dates late: " + songaytratre + "\n Fine: " + tienphatkynay + "vnd" 
                + "\n Total debt: " + tongno + "vnd");
           doc.add(p5);
           doc.add(p2);
   
           doc.add(p2);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a = JOptionPane.showConfirmDialog(null, "Printed successfully! Do you want to read the bill?", "Info", JOptionPane.YES_NO_OPTION);
                        
        if (a == 0){
            try
            {
                if ((new File(path+"PHIEUTRASACHSO"+maphieutrasach+".pdf")).exists()){
                    Process p = Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + path +"PHIEUTRASACHSO"+maphieutrasach+".pdf");
                                    
                }else{
                    JOptionPane.showMessageDialog(null, "File isn't exist.");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_phieutrasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_phieutrasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_phieutrasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_phieutrasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_phieutrasach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReload;
    private javax.swing.JTable classTableModel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
