package BooksManager.lm_view;

import lm_model.mdl_thongtinsach;
import BooksManager.lm_controller.ctl_add;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

public class jf_add extends javax.swing.JFrame implements ActionListener {

    public jf_add(mdl_thongtinsach thongtinsach){
        initComponents();
        setVisible(true);
        ctl_add controller = new ctl_add(btnSave, btnExit, jtfMaSach, jtfTenSach, jtfMaTheLoai, jtfMaTacGia, jtfNamXuatBan, jtfNhaXuatBan, jdcNgayNhap, jtfTriGia, jtfTinhTrang, jcbDaMuon, jlbMsg);
        controller.setView(thongtinsach);
        this.setLocationRelativeTo(null);
        this.setTitle("Change or add books");
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jlbMsg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfMaSach = new javax.swing.JTextField();
        jtfTenSach = new javax.swing.JTextField();
        jtfMaTheLoai = new javax.swing.JTextField();
        jtfMaTacGia = new javax.swing.JTextField();
        jcbDaMuon = new javax.swing.JCheckBox();
        jtfNamXuatBan = new javax.swing.JTextField();
        jtfNhaXuatBan = new javax.swing.JTextField();
        jtfTriGia = new javax.swing.JTextField();
        jtfTinhTrang = new javax.swing.JTextField();
        jdcNgayNhap = new com.toedter.calendar.JDateChooser();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(251, 224, 196));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        btnSave.setBackground(new java.awt.Color(138, 182, 214));
        btnSave.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jlbMsg.setFont(new java.awt.Font("SF Pro Display", 3, 14)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 51));

        jPanel2.setBackground(new java.awt.Color(251, 224, 196));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SF Pro Display", 1, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(138, 182, 214));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel1.setText("Mã sách:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 33, -1, -1));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel2.setText("Tên sách:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel3.setText("Mã thể loại:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 88, -1, -1));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel4.setText("Mã tác giả:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, -1, -1));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel5.setText("Năm xuất bản:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 149, -1, -1));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel6.setText("Nhà xuất bản:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 178, -1, -1));

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel7.setText("Ngày nhập:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 33, -1, -1));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel8.setText("Trị giá:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jLabel9.setText("Tình trạng:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 88, -1, -1));

        jtfMaSach.setEditable(false);
        jPanel2.add(jtfMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 32, 110, -1));
        jPanel2.add(jtfTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 59, 110, -1));
        jPanel2.add(jtfMaTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 87, 110, -1));
        jPanel2.add(jtfMaTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 113, 110, -1));

        jcbDaMuon.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jcbDaMuon.setText("Đã mượn");
        jPanel2.add(jcbDaMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 110, -1, -1));
        jPanel2.add(jtfNamXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 148, 212, -1));
        jPanel2.add(jtfNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 174, 212, 26));
        jPanel2.add(jtfTriGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 59, 75, -1));
        jPanel2.add(jtfTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 87, 75, -1));

        jdcNgayNhap.setDateFormatString("dd/MM/yyyy");
        jdcNgayNhap.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jPanel2.add(jdcNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 32, 99, -1));

        btnExit.setBackground(new java.awt.Color(138, 182, 214));
        btnExit.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(39, 39, 39))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon(this.getClass().getClassLoader().getResource("assets/books.png"));
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbDaMuon;
    public static com.toedter.calendar.JDateChooser jdcNgayNhap;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JTextField jtfMaSach;
    private javax.swing.JTextField jtfMaTacGia;
    private javax.swing.JTextField jtfMaTheLoai;
    public static javax.swing.JTextField jtfNamXuatBan;
    private javax.swing.JTextField jtfNhaXuatBan;
    private javax.swing.JTextField jtfTenSach;
    private javax.swing.JTextField jtfTinhTrang;
    private javax.swing.JTextField jtfTriGia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
             this.dispose();
    }
}
